//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Properties.String", typeof(String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        internal static string btnBrowse {
            get {
                return ResourceManager.GetString("btnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        internal static string btnCollect {
            get {
                return ResourceManager.GetString("btnCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo.
        /// </summary>
        internal static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        internal static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        internal static string btnSubmit {
            get {
                return ResourceManager.GetString("btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận xóa.
        /// </summary>
        internal static string Caption_Delete {
            get {
                return ResourceManager.GetString("Caption_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        internal static string Caption_Error {
            get {
                return ResourceManager.GetString("Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string Caption_Info {
            get {
                return ResourceManager.GetString("Caption_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string Caption_Noti {
            get {
                return ResourceManager.GetString("Caption_Noti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo.
        /// </summary>
        internal static string Caption_Warning {
            get {
                return ResourceManager.GetString("Caption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa file ở máy học sinh sau khi thu.
        /// </summary>
        internal static string cbDelete {
            get {
                return ResourceManager.GetString("cbDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        internal static string CPU {
            get {
                return ResourceManager.GetString("CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ổ cứng.
        /// </summary>
        internal static string Disk {
            get {
                return ResourceManager.GetString("Disk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương Thức Gửi Ảnh.
        /// </summary>
        internal static string gbSendImage {
            get {
                return ResourceManager.GetString("gbSendImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều chỉnh bài kiểm tra.
        /// </summary>
        internal static string gbSettingQuestion {
            get {
                return ResourceManager.GetString("gbSettingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bàn phím.
        /// </summary>
        internal static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lớp.
        /// </summary>
        internal static string lblClass {
            get {
                return ResourceManager.GetString("lblClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết thúc.
        /// </summary>
        internal static string lblEnd {
            get {
                return ResourceManager.GetString("lblEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp cần thu.
        /// </summary>
        internal static string lblFileCollect {
            get {
                return ResourceManager.GetString("lblFileCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File gửi.
        /// </summary>
        internal static string lblFileSend {
            get {
                return ResourceManager.GetString("lblFileSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục chứa.
        /// </summary>
        internal static string lblFolderCollect {
            get {
                return ResourceManager.GetString("lblFolderCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận về.
        /// </summary>
        internal static string lblFolderRecive {
            get {
                return ResourceManager.GetString("lblFolderRecive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi đến.
        /// </summary>
        internal static string lblFolderSend {
            get {
                return ResourceManager.GetString("lblFolderSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách phần mềm.
        /// </summary>
        internal static string lblListSoft {
            get {
                return ResourceManager.GetString("lblListSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm tối đa.
        /// </summary>
        internal static string lblMaxScore {
            get {
                return ResourceManager.GetString("lblMaxScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bài kiểm tra.
        /// </summary>
        internal static string lblNameExam {
            get {
                return ResourceManager.GetString("lblNameExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm.
        /// </summary>
        internal static string lblNameGroup {
            get {
                return ResourceManager.GetString("lblNameGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang Xử Lí.
        /// </summary>
        internal static string lblProcessing {
            get {
                return ResourceManager.GetString("lblProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chất Lượng Ảnh.
        /// </summary>
        internal static string lblQuality {
            get {
                return ResourceManager.GetString("lblQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi.
        /// </summary>
        internal static string lblQuestion {
            get {
                return ResourceManager.GetString("lblQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca.
        /// </summary>
        internal static string lblSession {
            get {
                return ResourceManager.GetString("lblSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt câu hỏi hiện tại.
        /// </summary>
        internal static string lblSettingThisQuestion {
            get {
                return ResourceManager.GetString("lblSettingThisQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu.
        /// </summary>
        internal static string lblStart {
            get {
                return ResourceManager.GetString("lblStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian trả lời.
        /// </summary>
        internal static string lblTimeanswer {
            get {
                return ResourceManager.GetString("lblTimeanswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian nghỉ giữa các câu.
        /// </summary>
        internal static string lblTimeToChangeQuestion {
            get {
                return ResourceManager.GetString("lblTimeToChangeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại câu hỏi.
        /// </summary>
        internal static string lblTypeQuestion {
            get {
                return ResourceManager.GetString("lblTypeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Lưu ý: nếu họ tên không có hãy nhấn reload. Nếu lớp không có hãy nhấn chọn và import file excel theo dạng chuẩn vào.
        /// </summary>
        internal static string lblWarning {
            get {
                return ResourceManager.GetString("lblWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đã được thêm thành công..
        /// </summary>
        internal static string Message_AddDataSuccess {
            get {
                return ResourceManager.GetString("Message_AddDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã phát đề.
        /// </summary>
        internal static string Message_AlreadyPassExam {
            get {
                return ResourceManager.GetString("Message_AlreadyPassExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang có bài thi diễn ra.
        /// </summary>
        internal static string Message_AnExamGoingOn {
            get {
                return ResourceManager.GetString("Message_AnExamGoingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã hủy nhập thời gian..
        /// </summary>
        internal static string Message_CancelTime {
            get {
                return ResourceManager.GetString("Message_CancelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa câu hỏi cuối cùng..
        /// </summary>
        internal static string Message_CantDeleteLastQuestion {
            get {
                return ResourceManager.GetString("Message_CantDeleteLastQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể chỉnh sữa câu hỏi của bài kiểm tra đang thi!.
        /// </summary>
        internal static string Message_CantEditQuestion {
            get {
                return ResourceManager.GetString("Message_CantEditQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi thành công.
        /// </summary>
        internal static string Message_ChangeSuccess {
            get {
                return ResourceManager.GetString("Message_ChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi thời gian làm cho câu hỏi thành công.
        /// </summary>
        internal static string Message_ChangeTimeQuestionSuccess {
            get {
                return ResourceManager.GetString("Message_ChangeTimeQuestionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi loại câu hỏi thành công.
        /// </summary>
        internal static string Message_ChangeTypeQuestionSuccess {
            get {
                return ResourceManager.GetString("Message_ChangeTypeQuestionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa câu hỏi này không?.
        /// </summary>
        internal static string Message_ConfirmDeleteQuestion {
            get {
                return ResourceManager.GetString("Message_ConfirmDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm đã được xóa..
        /// </summary>
        internal static string Message_DeleteGroup {
            get {
                return ResourceManager.GetString("Message_DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên tệp cần thu thập..
        /// </summary>
        internal static string Message_EnterFileToCollect {
            get {
                return ResourceManager.GetString("Message_EnterFileToCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập đường dẫn thư mục nguồn của tệp..
        /// </summary>
        internal static string Message_EnterFolderCollect {
            get {
                return ResourceManager.GetString("Message_EnterFolderCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn thư mục đích để lưu trữ..
        /// </summary>
        internal static string Message_EnterFolderSave {
            get {
                return ResourceManager.GetString("Message_EnterFolderSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Vui lòng nhập tên nhóm..
        /// </summary>
        internal static string Message_EnterNameGroup {
            get {
                return ResourceManager.GetString("Message_EnterNameGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian kết thúc phải lớn hơn thời gian bắt đầu..
        /// </summary>
        internal static string Message_ErrorTime {
            get {
                return ResourceManager.GetString("Message_ErrorTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài kiểm tra này có câu hỏi chưa cài đặt đáp án đúng.
        /// </summary>
        internal static string Message_ExamNotHaveAnswer {
            get {
                return ResourceManager.GetString("Message_ExamNotHaveAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm này đã tồn tại. Vui lòng chọn tên khác..
        /// </summary>
        internal static string Message_ExitGroup {
            get {
                return ResourceManager.GetString("Message_ExitGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File đã tồn tại trong danh sách..
        /// </summary>
        internal static string Message_ExitingFile {
            get {
                return ResourceManager.GetString("Message_ExitingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất file Excel thành công!.
        /// </summary>
        internal static string Message_ExportSuccess {
            get {
                return ResourceManager.GetString("Message_ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp không tồn tại:.
        /// </summary>
        internal static string Message_FileNotExit {
            get {
                return ResourceManager.GetString("Message_FileNotExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có sinh viên nào sẵn sàng!.
        /// </summary>
        internal static string Message_HaventReadyStudent {
            get {
                return ResourceManager.GetString("Message_HaventReadyStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin sinh viên không hợp lệ, vui lòng kiểm tra lại..
        /// </summary>
        internal static string Message_InfoStudenIssue {
            get {
                return ResourceManager.GetString("Message_InfoStudenIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có đề nào được phát.
        /// </summary>
        internal static string Message_IssuePassExam {
            get {
                return ResourceManager.GetString("Message_IssuePassExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mất kết nối với:.
        /// </summary>
        internal static string Message_LostConnect {
            get {
                return ResourceManager.GetString("Message_LostConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có thông tin học sinh..
        /// </summary>
        internal static string Message_NoHaveStudent {
            get {
                return ResourceManager.GetString("Message_NoHaveStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có câu hỏi cho loại này.
        /// </summary>
        internal static string Message_NoHaveTypeQuestion {
            get {
                return ResourceManager.GetString("Message_NoHaveTypeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian không đúng định dạng HH:mm. Vui lòng thử lại..
        /// </summary>
        internal static string Message_NotTrueTime {
            get {
                return ResourceManager.GetString("Message_NotTrueTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chưa tồn tại vui lòng liên hệ khoa để biết thêm thông tin.
        /// </summary>
        internal static string Message_NullRoom {
            get {
                return ResourceManager.GetString("Message_NullRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi chưa xác định đáp án đúng!.
        /// </summary>
        internal static string Message_QuestionNoHaveAnswer {
            get {
                return ResourceManager.GetString("Message_QuestionNoHaveAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các tệp đã được nhận và lưu thành công tại:.
        /// </summary>
        internal static string Message_ReciveSuccess {
            get {
                return ResourceManager.GetString("Message_ReciveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn lớp học..
        /// </summary>
        internal static string Message_SelectClass {
            get {
                return ResourceManager.GetString("Message_SelectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ít nhất một máy tính để tạo nhóm..
        /// </summary>
        internal static string Message_SelectCom {
            get {
                return ResourceManager.GetString("Message_SelectCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn thời gian kết thúc..
        /// </summary>
        internal static string Message_SelectEndTime {
            get {
                return ResourceManager.GetString("Message_SelectEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn mục cần xóa..
        /// </summary>
        internal static string Message_SelectFileToDelete {
            get {
                return ResourceManager.GetString("Message_SelectFileToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn tệp trước khi khởi động..
        /// </summary>
        internal static string Message_SelectFileToOpen {
            get {
                return ResourceManager.GetString("Message_SelectFileToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ít nhất một tệp để gửi..
        /// </summary>
        internal static string Message_SelectFileToSend {
            get {
                return ResourceManager.GetString("Message_SelectFileToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ được chọn 1 máy để trình chiếu!!.
        /// </summary>
        internal static string Message_SelectOneComSlideShow {
            get {
                return ResourceManager.GetString("Message_SelectOneComSlideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ít nhất một sinh viên..
        /// </summary>
        internal static string Message_SelectOneStudent {
            get {
                return ResourceManager.GetString("Message_SelectOneStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn buổi học..
        /// </summary>
        internal static string Message_SelectSession {
            get {
                return ResourceManager.GetString("Message_SelectSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn thời gian bắt đầu..
        /// </summary>
        internal static string Message_SelectStartTime {
            get {
                return ResourceManager.GetString("Message_SelectStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn một sinh viên từ bảng điểm danh để kiểm tra máy!!.
        /// </summary>
        internal static string Message_SelectStudentCheck {
            get {
                return ResourceManager.GetString("Message_SelectStudentCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ít nhất một sinh viên để thêm..
        /// </summary>
        internal static string Message_SelectStudentToAdd {
            get {
                return ResourceManager.GetString("Message_SelectStudentToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một dòng để gửi tín hiệu..
        /// </summary>
        internal static string Message_SelectToSendSignal {
            get {
                return ResourceManager.GetString("Message_SelectToSendSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn người dùng..
        /// </summary>
        internal static string Message_SelectUser {
            get {
                return ResourceManager.GetString("Message_SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu thi đề:.
        /// </summary>
        internal static string Message_StartExam {
            get {
                return ResourceManager.GetString("Message_StartExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc áp dụng cài đặt trên cho toàn bộ câu hỏi?.
        /// </summary>
        internal static string Message_SureAboutThisSetting {
            get {
                return ResourceManager.GetString("Message_SureAboutThisSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn hủy thi?. Mọi thông tin lựa chọn của sinh viên sẽ không được lưu lại!.
        /// </summary>
        internal static string Message_SureToCancelExam {
            get {
                return ResourceManager.GetString("Message_SureToCancelExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thành công.
        /// </summary>
        internal static string Messave_SaveSuccess {
            get {
                return ResourceManager.GetString("Messave_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng thiếu vị trí câu hỏi.
        /// </summary>
        internal static string Messsage_PositionQuestion {
            get {
                return ResourceManager.GetString("Messsage_PositionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin sai lệch.
        /// </summary>
        internal static string MismathInfo {
            get {
                return ResourceManager.GetString("MismathInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màn hình.
        /// </summary>
        internal static string Monitor {
            get {
                return ResourceManager.GetString("Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuột.
        /// </summary>
        internal static string Mouse {
            get {
                return ResourceManager.GetString("Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên máy.
        /// </summary>
        internal static string NameComputer {
            get {
                return ResourceManager.GetString("NameComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi đến từng máy (ảnh nhận đủ nhưng tốc độ chậm).
        /// </summary>
        internal static string radTCP {
            get {
                return ResourceManager.GetString("radTCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi đến nhìu máy (dễ mất ảnh nếu mạng yếu).
        /// </summary>
        internal static string radUDP {
            get {
                return ResourceManager.GetString("radUDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ram.
        /// </summary>
        internal static string Ram {
            get {
                return ResourceManager.GetString("Ram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSSV.
        /// </summary>
        internal static string StudentID {
            get {
                return ResourceManager.GetString("StudentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm danh.
        /// </summary>
        internal static string tsAttendance {
            get {
                return ResourceManager.GetString("tsAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu tệp.
        /// </summary>
        internal static string tsCollect {
            get {
                return ResourceManager.GetString("tsCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo nhóm.
        /// </summary>
        internal static string tsCreateGroup {
            get {
                return ResourceManager.GetString("tsCreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thi.
        /// </summary>
        internal static string tsExam {
            get {
                return ResourceManager.GetString("tsExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất file Excel.
        /// </summary>
        internal static string tsExport {
            get {
                return ResourceManager.GetString("tsExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất file điểm danh.
        /// </summary>
        internal static string tsExportAttendance {
            get {
                return ResourceManager.GetString("tsExportAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất file phiên.
        /// </summary>
        internal static string tsExportSession {
            get {
                return ResourceManager.GetString("tsExportSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string tsHome {
            get {
                return ResourceManager.GetString("tsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa.
        /// </summary>
        internal static string tsLock {
            get {
                return ResourceManager.GetString("tsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lí lớp học.
        /// </summary>
        internal static string tsManageClass {
            get {
                return ResourceManager.GetString("tsManageClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở phần mềm.
        /// </summary>
        internal static string tsQuickLaunch {
            get {
                return ResourceManager.GetString("tsQuickLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ngẫu nhiên.
        /// </summary>
        internal static string tsRandom {
            get {
                return ResourceManager.GetString("tsRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách màn hình.
        /// </summary>
        internal static string tsScreen {
            get {
                return ResourceManager.GetString("tsScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi tệp.
        /// </summary>
        internal static string tsSend {
            get {
                return ResourceManager.GetString("tsSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi/thu tệp.
        /// </summary>
        internal static string tsSendAndCollect {
            get {
                return ResourceManager.GetString("tsSendAndCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình chiếu.
        /// </summary>
        internal static string tsSlideShow {
            get {
                return ResourceManager.GetString("tsSlideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu trình chiếu.
        /// </summary>
        internal static string tsStartSlideShow {
            get {
                return ResourceManager.GetString("tsStartSlideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dừng trình chiếu.
        /// </summary>
        internal static string tsStopSlideShow {
            get {
                return ResourceManager.GetString("tsStopSlideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở Khóa.
        /// </summary>
        internal static string tsUnlock {
            get {
                return ResourceManager.GetString("tsUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string tsUpdate {
            get {
                return ResourceManager.GetString("tsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật điểm danh.
        /// </summary>
        internal static string tsUpdateAttendance {
            get {
                return ResourceManager.GetString("tsUpdateAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật phiên và điểm dânh.
        /// </summary>
        internal static string tsUpdateBoth {
            get {
                return ResourceManager.GetString("tsUpdateBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật phiên.
        /// </summary>
        internal static string tsUpdateInfoSession {
            get {
                return ResourceManager.GetString("tsUpdateInfoSession", resourceCulture);
            }
        }
    }
}
